tag: RealMotion_I

pl_module:
  _target_: realmotion.model.pl_modules.BaseLightningModule
  model:
    _target_: realmotion.model.realmotion.RealMotion_I
    embed_dim: 128
    future_steps: 40
    encoder_depth: 4
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: False
    drop_path: 0.2
  optim:
    lr: 1e-3
    weight_decay: 1e-2
    min_lr: 1e-5
    epochs: ${epochs}
    warmup_ratio: 0.167
