tag: av2

pl_module:
  _target_: realmotion.datamodules.av2_datamodule.Av2DataModule

  data_root: /dev_ws/src/tam_deep_prediction/data/raceverse-small-v2/realmotion_processed_I_20 # Root for training
  # data_root: /dev_ws/src/tam_deep_prediction/data/tum_av2_heading_90/realmotion_processed_I  #Root for inference
  train_batch_size: ${batch_size}
  test_batch_size: ${batch_size}
  shuffle: True
  num_workers: 8
  pin_memory: True
  dataset:
    num_historical_steps: 20
    split_points: [20]
    radius: 250.0
