tag: av2_3frame_30his

pl_module:
  _target_: realmotion.datamodules.av2_datamodule.Av2DataModule

  data_root: /dev_ws/src/tam_deep_prediction/data/raceverse-small-v2/realmotion_processed
  train_batch_size: ${batch_size}
  test_batch_size: ${batch_size}
  shuffle: True
  num_workers: 8
  pin_memory: True
  dataset:
    num_historical_steps: 20
    split_points: [30, 40, 50]
    radius: 250.0
